apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  labels:
    type: nfs
    storage: nfs
provisioner: example.com/nfs
volumeBindingMode: WaitForFirstConsumer
parameters:
  archiveOnDelete: "false"