apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-vol
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /vol/mongo

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-vol
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
