apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
      - name: owncloud
        image: owncloud/server:latest
        #image: registry.tcema.tc.br/nextcloud:latest
        #image:  registry.example.com/cmattos/owncloud_server:latest
        #image:  registry.example.com/cmattos/site:owncloud108_1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   namespace: default
#   name: nextcloud
# spec:
#   selector:
#     matchLabels:
#       app: nextcloud
#   template:
#     metadata:
#       labels:
#         app: nextcloud
#     spec: 
#       containers:       
#         - name: nextcloud
#           image: nextcloud:latest
#           resources:
#             limits:
#              memory: "128Mi"
#              cpu: "500m"
#           ports:
#           - containerPort: 8080