version: '3'

services:
  registry:
    image: registry:2
    ports:
    - "443:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd 
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.example.com.crt 
      REGISTRY_HTTP_TLS_KEY: /certs/docker-registry.key 
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./data:/data
      #- ./registry:/registry
