apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressv2
  annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: srv02.tce.ma.gov.br
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: owncloud
                port:
                  number: 80
          - path: /nextcloud
            pathType: Prefix
            backend:
              service:
                name: nextcloud
                port:
                  number: 80