apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LmV4YW1wbGUuY29tIjp7InVzZXJuYW1lIjoiY21hdHRvcyIsInBhc3N3b3JkIjoiMTIzIiwiZW1haWwiOiJjbWF0dG9zNThAZ21haWwuY29tIiwiYXV0aCI6IlkyMWhkSFJ2Y3pveE1qTT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2022-08-21T12:06:07Z"
  name: regcred
  namespace: default
  resourceVersion: "3644158"
  uid: 82c0f9ac-9567-43f4-aa3a-aec753d78e17
type: kubernetes.io/dockerconfigjson
