apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
  #type: LoadBalancer
  clusterIP: 10.98.171.117
  externalIPs:
    - 172.16.0.41